# Generated by Django 5.1.7 on 2025-03-20 02:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='survey',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='options_cssclass',
            field=models.CharField(blank=True, default='col-sm-6 col-md-4 col-lg-3 col-xl-2 mb-3', max_length=500),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='surveyoption',
            name='color',
            field=models.CharField(default='#f8f9fa', max_length=7),
        ),
        migrations.AlterField(
            model_name='surveyoption',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='surveyoption',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
