# Generated by Django 5.2.5 on 2025-08-11 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_survey_description_alter_survey_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='requires_authentication',
            field=models.BooleanField(default=True, help_text='Whether users need to be authenticated to vote on this survey.'),
        ),
        migrations.AddField(
            model_name='surveychoice',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='surveychoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_choices', to=settings.AUTH_USER_MODEL),
        ),
    ]
